version: '2'
services: 
  web:
    image: odoo:13.0
    depends_on: 
      - mydb
    ports:
      - "8069:8069"
    environment: 
      - HOST=mydb
      - USER=odoo
      - PASSWORD=odoopw

  mydb:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoopw
      - POSTGRES_USER=odoo
